const CARD_POOL = [
  { id: "unit_lizard", name: "コモンリザード", cost: 1, atk: 1, hp: 2, type: "unit", evolvesTo: "evo_lizard" },
  { id: "unit_tortoise", name: "バブルトータス", cost: 2, atk: 2, hp: 3, type: "unit", evolvesTo: "evo_tortoise" },
  { id: "unit_cat", name: "フォレストキャット", cost: 1, atk: 2, hp: 1, type: "unit", evolvesTo: "evo_cat" },
  { id: "unit_knight", name: "ナイトフェンサー", cost: 3, atk: 3, hp: 4, type: "unit" },
  { id: "unit_guard_golem", name: "ガードゴーレム", cost: 2, atk: 1, hp: 4, type: "unit", keywords: ["ward"], evolvesTo: "evo_guard_golem" },
  { id: "unit_quick_raptor", name: "クイックラプトル", cost: 2, atk: 2, hp: 2, type: "unit", keywords: ["rush"], evolvesTo: "evo_raptor" },
  { id: "unit_sky_drake", name: "スカイドレイク", cost: 5, atk: 4, hp: 4, type: "unit", keywords: ["storm"], evolvesTo: "evo_sky_drake" },
  { id: "unit_scholar_owl", name: "スカラーオウル", cost: 2, atk: 2, hp: 2, type: "unit", onPlay: [{ type: "draw", amount: 1 }], evolvesTo: "evo_scholar" },
  { id: "unit_alchemist_fox", name: "アルケミーフォックス", cost: 3, atk: 2, hp: 3, type: "unit", onPlay: [{ type: "damage_random_enemy_unit", amount: 2 }], evolvesTo: "evo_alchemist" },
  { id: "unit_priest_deer", name: "プリーストディア", cost: 3, atk: 2, hp: 4, type: "unit", onPlay: [{ type: "heal_leader", amount: 2 }] },
  { id: "unit_seed_sprite", name: "シードスプライト", cost: 1, atk: 1, hp: 1, type: "unit", onPlay: [{ type: "summon", cardId: "token_fairy", count: 1 }] },
  { id: "unit_drum_bear", name: "ドラムベア", cost: 4, atk: 3, hp: 5, type: "unit", onPlay: [{ type: "buff_all_allies", atk: 1, hp: 0 }] },
  { id: "unit_frost_witch", name: "フロストウィッチ", cost: 4, atk: 3, hp: 3, type: "unit", onPlay: [{ type: "damage_all_enemy_units", amount: 1 }] },
  { id: "unit_iron_colossus", name: "アイアンコロッサス", cost: 6, atk: 5, hp: 7, type: "unit", keywords: ["ward"] },
  { id: "unit_mana_slime", name: "マナスライム", cost: 2, atk: 1, hp: 3, type: "unit", onPlay: [{ type: "gain_pp", amount: 1 }] },
  { id: "unit_necro_wolf", name: "ネクロウルフ", cost: 4, atk: 4, hp: 3, type: "unit", onDeath: [{ type: "damage_enemy_leader", amount: 2 }] },
  { id: "unit_blade_angel", name: "ブレードエンジェル", cost: 5, atk: 3, hp: 5, type: "unit", keywords: ["storm"] },
  { id: "unit_sentinel_crab", name: "センチネルクラブ", cost: 3, atk: 2, hp: 5, type: "unit", keywords: ["ward"] },

  { id: "spell_heal", name: "ヒールベリー", cost: 2, type: "spell", effects: [{ type: "heal_leader", amount: 3 }] },
  { id: "spell_fire", name: "ファイアボルト", cost: 2, type: "spell", effects: [{ type: "damage_enemy_unit_or_leader", amount: 3, leaderFallback: 2 }] },
  { id: "spell_lightning", name: "ライトニングスピア", cost: 3, type: "spell", effects: [{ type: "damage_random_enemy_unit", amount: 4 }] },
  { id: "spell_blizzard", name: "ブリザードノヴァ", cost: 4, type: "spell", effects: [{ type: "damage_all_enemy_units", amount: 2 }] },
  { id: "spell_inspiration", name: "インスピレーション", cost: 2, type: "spell", effects: [{ type: "draw", amount: 2 }] },
  { id: "spell_call_fairy", name: "フェアリーコール", cost: 2, type: "spell", effects: [{ type: "summon", cardId: "token_fairy", count: 2 }] },
  { id: "spell_reanimate", name: "リアニメイト", cost: 4, type: "spell", effects: [{ type: "summon", cardId: "token_zombie", count: 2 }] },
  { id: "spell_assassinate", name: "アサシネイト", cost: 5, type: "spell", effects: [{ type: "destroy_enemy_highest_atk" }] },
  { id: "spell_soul_drain", name: "ソウルドレイン", cost: 3, type: "spell", effects: [{ type: "damage_enemy_leader", amount: 3 }, { type: "heal_leader", amount: 2 }] },
  { id: "spell_blessing", name: "ユニオンブレッシング", cost: 2, type: "spell", effects: [{ type: "buff_all_allies", atk: 1, hp: 1 }] },
  { id: "spell_meteor", name: "メテオストライク", cost: 6, type: "spell", effects: [{ type: "damage_enemy_unit_or_leader", amount: 6, leaderFallback: 4 }] },
  { id: "spell_hymn", name: "ホーリーヒム", cost: 3, type: "spell", effects: [{ type: "heal_all_allies", amount: 2 }] },
  { id: "spell_arcane", name: "アーケインミスト", cost: 1, type: "spell", effects: [{ type: "damage_random_enemy_unit", amount: 1 }, { type: "draw", amount: 1 }] },

  { id: "evo_lizard", name: "リザードン改", cost: 2, atk: 4, hp: 5, type: "evolution", evolvesFrom: "unit_lizard", grantsKeywords: ["storm"] },
  { id: "evo_tortoise", name: "ハイドロトータス", cost: 2, atk: 4, hp: 6, type: "evolution", evolvesFrom: "unit_tortoise", grantsKeywords: ["ward"] },
  { id: "evo_cat", name: "フォレストリンクス", cost: 2, atk: 4, hp: 3, type: "evolution", evolvesFrom: "unit_cat", grantsKeywords: ["storm"] },
  { id: "evo_guard_golem", name: "フォートレスゴーレム", cost: 2, atk: 3, hp: 7, type: "evolution", evolvesFrom: "unit_guard_golem", grantsKeywords: ["ward"] },
  { id: "evo_raptor", name: "スラッシュラプトル", cost: 2, atk: 5, hp: 4, type: "evolution", evolvesFrom: "unit_quick_raptor", grantsKeywords: ["storm"] },
  { id: "evo_sky_drake", name: "テンペストドラゴン", cost: 3, atk: 7, hp: 6, type: "evolution", evolvesFrom: "unit_sky_drake", grantsKeywords: ["storm"] },
  { id: "evo_scholar", name: "アークオウル", cost: 2, atk: 4, hp: 4, type: "evolution", evolvesFrom: "unit_scholar_owl", onEvolve: [{ type: "draw", amount: 1 }] },
  { id: "evo_alchemist", name: "エルダーアルケミー", cost: 2, atk: 4, hp: 5, type: "evolution", evolvesFrom: "unit_alchemist_fox", onEvolve: [{ type: "damage_all_enemy_units", amount: 1 }] },

  { id: "token_fairy", name: "フェアリー", cost: 1, atk: 1, hp: 1, type: "unit", collectible: false },
  { id: "token_zombie", name: "ゾンビ", cost: 1, atk: 2, hp: 1, type: "unit", keywords: ["rush"], collectible: false }
];
