const CARD_POOL = [
  { id: "unit_lizard", name: "コモンリザード", cost: 1, atk: 1, hp: 2, type: "unit", tags: ["dragon"], evolvesTo: "evo_lizard" },
  { id: "unit_tortoise", name: "バブルトータス", cost: 2, atk: 2, hp: 3, type: "unit", tags: ["sea"], evolvesTo: "evo_tortoise" },
  { id: "unit_cat", name: "フォレストキャット", cost: 1, atk: 2, hp: 1, type: "unit", tags: ["forest"], evolvesTo: "evo_cat" },
  { id: "unit_knight", name: "ナイトフェンサー", cost: 3, atk: 3, hp: 4, type: "unit", tags: ["neutral"] },
  { id: "unit_guard_golem", name: "ガードゴーレム", cost: 2, atk: 1, hp: 4, type: "unit", tags: ["neutral"], keywords: ["ward"], evolvesTo: "evo_guard_golem" },
  { id: "unit_quick_raptor", name: "クイックラプトル", cost: 2, atk: 2, hp: 2, type: "unit", tags: ["dragon"], keywords: ["rush"], evolvesTo: "evo_raptor" },
  {
    id: "unit_sky_drake",
    name: "スカイドレイク",
    cost: 5,
    atk: 4,
    hp: 4,
    type: "unit",
    tags: ["dragon"],
    keywords: ["storm"],
    combo: { tag: "dragon", threshold: 2, text: "連携2: 味方全体+1/0", effects: [{ type: "buff_all_allies", atk: 1, hp: 0 }] },
    evolvesTo: "evo_sky_drake"
  },
  { id: "unit_scholar_owl", name: "スカラーオウル", cost: 2, atk: 2, hp: 2, type: "unit", tags: ["holy"], onPlay: [{ type: "draw", amount: 1 }], evolvesTo: "evo_scholar" },
  { id: "unit_alchemist_fox", name: "アルケミーフォックス", cost: 3, atk: 2, hp: 3, type: "unit", tags: ["shadow"], onPlay: [{ type: "damage_random_enemy_unit", amount: 2 }], evolvesTo: "evo_alchemist" },
  { id: "unit_priest_deer", name: "プリーストディア", cost: 3, atk: 2, hp: 4, type: "unit", tags: ["holy"], onPlay: [{ type: "heal_leader", amount: 2 }], evolvesTo: "evo_priest_deer" },
  { id: "unit_seed_sprite", name: "シードスプライト", cost: 1, atk: 1, hp: 1, type: "unit", tags: ["forest"], onPlay: [{ type: "summon", cardId: "token_fairy", count: 1 }] },
  { id: "unit_drum_bear", name: "ドラムベア", cost: 4, atk: 3, hp: 5, type: "unit", tags: ["neutral"], onPlay: [{ type: "buff_all_allies", atk: 1, hp: 0 }] },
  { id: "unit_frost_witch", name: "フロストウィッチ", cost: 4, atk: 3, hp: 3, type: "unit", tags: ["sea"], onPlay: [{ type: "damage_all_enemy_units", amount: 1 }] },
  { id: "unit_iron_colossus", name: "アイアンコロッサス", cost: 6, atk: 5, hp: 7, type: "unit", tags: ["neutral"], keywords: ["ward"] },
  { id: "unit_mana_slime", name: "マナスライム", cost: 2, atk: 1, hp: 3, type: "unit", tags: ["sea"], onPlay: [{ type: "gain_pp", amount: 1 }] },
  {
    id: "unit_necro_wolf",
    name: "ネクロウルフ",
    cost: 4,
    atk: 4,
    hp: 3,
    type: "unit",
    tags: ["shadow"],
    onDeath: [{ type: "damage_enemy_leader", amount: 2 }],
    combo: { tag: "shadow", threshold: 2, text: "連携2: 相手リーダーに1ダメージ", effects: [{ type: "damage_enemy_leader", amount: 1 }] }
  },
  { id: "unit_blade_angel", name: "ブレードエンジェル", cost: 5, atk: 3, hp: 5, type: "unit", tags: ["holy"], keywords: ["storm"], evolvesTo: "evo_blade_angel" },
  { id: "unit_sentinel_crab", name: "センチネルクラブ", cost: 3, atk: 2, hp: 5, type: "unit", tags: ["sea"], keywords: ["ward"], evolvesTo: "evo_sentinel_crab" },
  {
    id: "unit_venge_dragon",
    name: "ヴェンジドラゴン",
    cost: 5,
    atk: 4,
    hp: 4,
    type: "unit",
    tags: ["dragon"],
    keywords: ["storm"],
    awakening: { hpAtMost: 10, text: "覚醒: 相手リーダーに3ダメージ", effects: [{ type: "damage_enemy_leader", amount: 3 }] }
  },
  { id: "unit_bramble_guard", name: "ブランブルガード", cost: 2, atk: 1, hp: 5, type: "unit", tags: ["forest"], keywords: ["ward"], evolvesTo: "evo_bramble_guard" },
  { id: "unit_moon_blade", name: "ムーンブレード", cost: 3, atk: 3, hp: 2, type: "unit", tags: ["holy"], keywords: ["rush"], evolvesTo: "evo_moon_blade" },
  { id: "unit_grave_baron", name: "グレイブバロン", cost: 5, atk: 4, hp: 4, type: "unit", tags: ["shadow"], onPlay: [{ type: "summon", cardId: "token_zombie", count: 1 }], evolvesTo: "evo_grave_baron" },
  {
    id: "unit_eternal_jouma",
    name: "エターナルじょうま",
    cost: 8,
    atk: 7,
    hp: 7,
    type: "unit",
    tags: ["neutral"],
    onPlay: [{ type: "destroy_all_other_units" }],
    collectible: false
  },
  {
    id: "unit_lion_champion",
    name: "獅王の先鋒",
    cost: 5,
    atk: 5,
    hp: 6,
    type: "unit",
    tags: ["neutral"],
    keywords: ["storm"],
    onPlay: [{ type: "damage_enemy_leader", amount: 2 }],
    collectible: false
  },
  {
    id: "spell_lion_command",
    name: "王者の号令",
    cost: 2,
    type: "spell",
    tags: ["neutral"],
    effects: [
      { type: "damage_enemy_unit_or_leader", amount: 4, leaderFallback: 3 },
      { type: "draw", amount: 1 }
    ],
    collectible: false
  },
  {
    id: "spell_lion_wrath",
    name: "百獣の粛清",
    cost: 4,
    type: "spell",
    tags: ["neutral"],
    effects: [
      { type: "destroy_enemy_highest_atk" },
      { type: "damage_all_enemy_units", amount: 2 }
    ],
    collectible: false
  },

  { id: "spell_heal", name: "ヒールベリー", cost: 2, type: "spell", tags: ["holy"], effects: [{ type: "heal_leader", amount: 3 }] },
  { id: "spell_fire", name: "ファイアボルト", cost: 2, type: "spell", tags: ["dragon"], effects: [{ type: "damage_enemy_unit_or_leader", amount: 3, leaderFallback: 2 }] },
  { id: "spell_lightning", name: "ライトニングスピア", cost: 3, type: "spell", tags: ["sea"], effects: [{ type: "damage_random_enemy_unit", amount: 4 }] },
  { id: "spell_blizzard", name: "ブリザードノヴァ", cost: 4, type: "spell", tags: ["sea"], effects: [{ type: "damage_all_enemy_units", amount: 2 }] },
  { id: "spell_inspiration", name: "インスピレーション", cost: 2, type: "spell", tags: ["holy"], effects: [{ type: "draw", amount: 2 }] },
  {
    id: "spell_call_fairy",
    name: "フェアリーコール",
    cost: 2,
    type: "spell",
    tags: ["forest"],
    effects: [{ type: "summon", cardId: "token_fairy", count: 2 }],
    combo: { tag: "forest", threshold: 3, text: "連携3: フェアリーをさらに1体", effects: [{ type: "summon", cardId: "token_fairy", count: 1 }] }
  },
  { id: "spell_reanimate", name: "リアニメイト", cost: 4, type: "spell", tags: ["shadow"], effects: [{ type: "summon", cardId: "token_zombie", count: 2 }] },
  { id: "spell_assassinate", name: "アサシネイト", cost: 5, type: "spell", tags: ["shadow"], effects: [{ type: "destroy_enemy_highest_atk" }] },
  { id: "spell_soul_drain", name: "ソウルドレイン", cost: 3, type: "spell", tags: ["shadow"], effects: [{ type: "damage_enemy_leader", amount: 3 }, { type: "heal_leader", amount: 2 }] },
  { id: "spell_blessing", name: "ユニオンブレッシング", cost: 2, type: "spell", tags: ["holy"], effects: [{ type: "buff_all_allies", atk: 1, hp: 1 }] },
  { id: "spell_meteor", name: "メテオストライク", cost: 6, type: "spell", tags: ["dragon"], effects: [{ type: "damage_enemy_unit_or_leader", amount: 6, leaderFallback: 4 }] },
  { id: "spell_hymn", name: "ホーリーヒム", cost: 3, type: "spell", tags: ["holy"], effects: [{ type: "heal_all_allies", amount: 2 }] },
  { id: "spell_arcane", name: "アーケインミスト", cost: 1, type: "spell", tags: ["shadow"], effects: [{ type: "damage_random_enemy_unit", amount: 1 }, { type: "draw", amount: 1 }] },
  {
    id: "spell_last_resort",
    name: "ラストリゾート",
    cost: 2,
    type: "spell",
    tags: ["shadow"],
    effects: [{ type: "damage_enemy_unit_or_leader", amount: 2, leaderFallback: 2 }],
    awakening: { hpAtMost: 10, text: "覚醒: 1ドローして相手リーダーに2ダメージ", effects: [{ type: "draw", amount: 1 }, { type: "damage_enemy_leader", amount: 2 }] }
  },
  {
    id: "spell_reversal",
    name: "リバーサルグレイス",
    cost: 4,
    type: "spell",
    tags: ["holy"],
    effects: [{ type: "heal_leader", amount: 3 }],
    awakening: { hpAtMost: 10, text: "覚醒: 相手全体に2ダメージ", effects: [{ type: "damage_all_enemy_units", amount: 2 }] }
  },
  { id: "spell_tactical_draw", name: "タクティカルドロー", cost: 1, type: "spell", tags: ["neutral"], effects: [{ type: "draw", amount: 1 }, { type: "buff_random_ally", atk: 1, hp: 0 }] },
  { id: "spell_dragon_roar", name: "ドラゴンロアー", cost: 3, type: "spell", tags: ["dragon"], effects: [{ type: "damage_enemy_leader", amount: 2 }, { type: "draw", amount: 1 }] },
  { id: "spell_growth_signal", name: "グロースシグナル", cost: 2, type: "spell", tags: ["forest"], effects: [{ type: "summon", cardId: "token_fairy", count: 1 }, { type: "buff_random_ally", atk: 1, hp: 1 }] },
  {
    id: "token_coin",
    name: "コイン",
    cost: 0,
    type: "spell",
    tags: ["neutral"],
    effects: [{ type: "coin_pp", amount: 1 }],
    collectible: false
  },
  {
    id: "token_jouma_tears",
    name: "じょうまの涙",
    cost: 0,
    type: "spell",
    tags: ["neutral"],
    effects: [{ type: "damage_random_enemy_unit", amount: 2 }],
    collectible: false
  },

  { id: "evo_lizard", name: "リザードン改", cost: 2, atk: 4, hp: 5, type: "evolution", tags: ["dragon"], evolvesFrom: "unit_lizard", grantsKeywords: ["storm"] },
  { id: "evo_tortoise", name: "ハイドロトータス", cost: 2, atk: 4, hp: 6, type: "evolution", tags: ["sea"], evolvesFrom: "unit_tortoise", grantsKeywords: ["ward"] },
  { id: "evo_cat", name: "フォレストリンクス", cost: 2, atk: 4, hp: 3, type: "evolution", tags: ["forest"], evolvesFrom: "unit_cat", grantsKeywords: ["storm"] },
  { id: "evo_guard_golem", name: "フォートレスゴーレム", cost: 2, atk: 3, hp: 7, type: "evolution", tags: ["neutral"], evolvesFrom: "unit_guard_golem", grantsKeywords: ["ward"] },
  { id: "evo_raptor", name: "スラッシュラプトル", cost: 2, atk: 5, hp: 4, type: "evolution", tags: ["dragon"], evolvesFrom: "unit_quick_raptor", grantsKeywords: ["storm"] },
  { id: "evo_sky_drake", name: "テンペストドラゴン", cost: 3, atk: 7, hp: 6, type: "evolution", tags: ["dragon"], evolvesFrom: "unit_sky_drake", grantsKeywords: ["storm"] },
  { id: "evo_scholar", name: "アークオウル", cost: 2, atk: 4, hp: 4, type: "evolution", tags: ["holy"], evolvesFrom: "unit_scholar_owl", onEvolve: [{ type: "draw", amount: 1 }] },
  { id: "evo_alchemist", name: "エルダーアルケミー", cost: 2, atk: 4, hp: 5, type: "evolution", tags: ["shadow"], evolvesFrom: "unit_alchemist_fox", onEvolve: [{ type: "damage_all_enemy_units", amount: 1 }] },
  { id: "evo_priest_deer", name: "セイントディア", cost: 2, atk: 4, hp: 6, type: "evolution", tags: ["holy"], evolvesFrom: "unit_priest_deer", onEvolve: [{ type: "heal_leader", amount: 3 }] },
  { id: "evo_sentinel_crab", name: "アビスセンチネル", cost: 2, atk: 4, hp: 7, type: "evolution", tags: ["sea"], evolvesFrom: "unit_sentinel_crab", grantsKeywords: ["ward"] },
  { id: "evo_blade_angel", name: "ヴァルキリーエンジェル", cost: 3, atk: 6, hp: 6, type: "evolution", tags: ["holy"], evolvesFrom: "unit_blade_angel", grantsKeywords: ["storm"] },
  { id: "evo_bramble_guard", name: "スパインブランブル", cost: 2, atk: 3, hp: 8, type: "evolution", tags: ["forest"], evolvesFrom: "unit_bramble_guard", grantsKeywords: ["ward"] },
  { id: "evo_moon_blade", name: "ルナブレード", cost: 2, atk: 5, hp: 4, type: "evolution", tags: ["holy"], evolvesFrom: "unit_moon_blade", grantsKeywords: ["storm"] },
  { id: "evo_grave_baron", name: "ナイトメアバロン", cost: 3, atk: 6, hp: 6, type: "evolution", tags: ["shadow"], evolvesFrom: "unit_grave_baron", onEvolve: [{ type: "summon", cardId: "token_zombie", count: 1 }] },

  { id: "token_fairy", name: "フェアリー", cost: 1, atk: 1, hp: 1, type: "unit", tags: ["forest"], collectible: false },
  { id: "token_zombie", name: "ゾンビ", cost: 1, atk: 2, hp: 1, type: "unit", tags: ["shadow"], keywords: ["rush"], collectible: false }
];
